import type { EditableFieldSpec } from "@/types/editableFields";

export const NORTHFIELD_EDITABLE_FIELDS: EditableFieldSpec[] = [
  { path: "top_bar.company_name", label: "Company name", type: "text", group: "Brand", maxLength: 50 },
  { path: "top_bar.license_text", label: "License line", type: "text", group: "Brand", maxLength: 80 },
  { path: "top_bar.availability_text", label: "Availability", type: "text", group: "Brand", maxLength: 60 },
  { path: "top_bar.phone_display", label: "Phone (display)", type: "text", group: "Brand" },

  { path: "hero.eyebrow", label: "Eyebrow", type: "text", group: "Hero", maxLength: 80 },
  { path: "hero.headline_line_1", label: "Headline line 1", type: "text", group: "Hero" },
  {
    path: "hero.headline_italic_word",
    label: "Italic accent word",
    type: "text",
    group: "Hero",
    hint: "This word renders in italic with your accent color.",
  },
  { path: "hero.headline_line_2", label: "Headline line 2", type: "text", group: "Hero" },
  { path: "hero.headline_line_3", label: "Headline line 3", type: "text", group: "Hero" },
  {
    path: "hero.headline_underlined",
    label: "Underlined phrase",
    type: "text",
    group: "Hero",
    hint: "This phrase gets the accent underline highlight.",
  },
  { path: "hero.lede", label: "Lead paragraph", type: "textarea", group: "Hero", maxLength: 500 },
  {
    path: "hero.meta_stats",
    label: "Hero stats",
    type: "repeater",
    group: "Hero",
    maxItems: 3,
    minItems: 3,
    locked: "count",
    itemSchema: [
      { field: "label", label: "Label", type: "text" },
      { field: "value", label: "Value", type: "text" },
    ],
  },

  { path: "quote_card.tag", label: "Form tag label", type: "text", group: "Quote Form", maxLength: 20 },
  { path: "quote_card.title", label: "Form title", type: "text", group: "Quote Form" },
  { path: "quote_card.subtitle", label: "Form subtitle", type: "text", group: "Quote Form" },
  { path: "quote_card.submit_label", label: "Submit button label", type: "text", group: "Quote Form" },
  { path: "quote_card.caption", label: "Form caption", type: "text", group: "Quote Form" },

  {
    path: "marquee.items",
    label: "Marquee items",
    type: "repeater",
    group: "Marquee",
    maxItems: 6,
    itemSchema: [
      { field: "text", label: "Text", type: "text" },
      { field: "accent_word", label: "Italic accent word (optional)", type: "text", optional: true },
    ],
  },

  { path: "stats.section_number", label: "Section label", type: "text", group: "Stats" },
  { path: "stats.section_title_prefix", label: "Stats section title (prefix)", type: "text", group: "Stats" },
  { path: "stats.section_title_italic", label: "Italic accent word", type: "text", group: "Stats" },
  { path: "stats.section_title_suffix", label: "Suffix", type: "text", group: "Stats" },
  {
    path: "stats.items",
    label: "Stat cards",
    type: "repeater",
    group: "Stats",
    minItems: 4,
    maxItems: 4,
    locked: "count",
    itemSchema: [
      { field: "number", label: "Number", type: "text" },
      { field: "superscript", label: "Superscript (optional)", type: "text", optional: true },
      { field: "label", label: "Label", type: "textarea", maxLength: 200 },
    ],
  },

  { path: "services.section_number", label: "Section label", type: "text", group: "Services" },
  { path: "services.intro", label: "Services intro", type: "textarea", group: "Services", maxLength: 400 },
  { path: "services.section_title_prefix", label: "Services title prefix", type: "text", group: "Services" },
  { path: "services.section_title_italic", label: "Italic accent", type: "text", group: "Services" },
  { path: "services.section_title_suffix", label: "Suffix", type: "text", group: "Services" },
  {
    path: "services.items",
    label: "Service cards",
    type: "repeater",
    group: "Services",
    minItems: 4,
    maxItems: 4,
    locked: "count",
    itemSchema: [
      { field: "number", label: "Number line", type: "text" },
      { field: "title_prefix", label: "Title prefix", type: "text" },
      { field: "title_italic", label: "Italic accent", type: "text" },
      { field: "title_suffix", label: "Title suffix", type: "text", optional: true },
      { field: "description", label: "Description", type: "textarea", maxLength: 320 },
      { field: "tags", label: "Tags", type: "tag-list", maxItems: 4 },
    ],
  },

  { path: "projects.section_number", label: "Section label", type: "text", group: "Projects" },
  { path: "projects.section_title_prefix", label: "Title prefix", type: "text", group: "Projects" },
  { path: "projects.section_title_italic", label: "Italic accent", type: "text", group: "Projects" },
  { path: "projects.section_title_suffix", label: "Suffix", type: "text", group: "Projects" },
  {
    path: "projects.items",
    label: "Projects",
    type: "repeater",
    group: "Projects",
    minItems: 1,
    maxItems: 5,
    itemSchema: [
      { field: "number", label: "Number", type: "text" },
      { field: "name_prefix", label: "Project name", type: "text" },
      { field: "name_italic", label: "Location (italic)", type: "text" },
      { field: "type_heading", label: "Type heading", type: "text" },
      { field: "type_detail", label: "Type detail", type: "text" },
      { field: "completed_heading", label: "Completed heading", type: "text" },
      { field: "completed_detail", label: "Completion", type: "text" },
      { field: "value", label: "Project value", type: "text" },
      { field: "image_url", label: "Project image", type: "image", optional: true, hint: "Leave blank to use abstract wireframe." },
    ],
  },

  { path: "process.section_number", label: "Section label", type: "text", group: "Process" },
  { path: "process.section_title_prefix", label: "Title prefix", type: "text", group: "Process" },
  { path: "process.section_title_italic", label: "Italic accent", type: "text", group: "Process" },
  { path: "process.section_title_suffix", label: "Suffix", type: "text", group: "Process" },
  {
    path: "process.steps",
    label: "Process steps",
    type: "repeater",
    group: "Process",
    minItems: 4,
    maxItems: 4,
    locked: "count",
    itemSchema: [
      { field: "number", label: "Step number", type: "text" },
      { field: "title_prefix", label: "Step title prefix", type: "text" },
      { field: "title_italic", label: "Italic accent", type: "text" },
      { field: "title_suffix", label: "Title suffix", type: "text", optional: true },
      { field: "description", label: "Description", type: "textarea", maxLength: 280 },
    ],
  },

  { path: "testimonial.quote_parts.opening", label: "Quote opening", type: "textarea", group: "Testimonial" },
  { path: "testimonial.quote_parts.italic_1", label: "First italic accent", type: "text", group: "Testimonial" },
  { path: "testimonial.quote_parts.middle", label: "Middle text", type: "textarea", group: "Testimonial" },
  { path: "testimonial.quote_parts.italic_2", label: "Second italic accent", type: "text", group: "Testimonial" },
  { path: "testimonial.quote_parts.closing", label: "Closing text", type: "textarea", group: "Testimonial" },
  { path: "testimonial.author_name", label: "Author name", type: "text", group: "Testimonial" },
  { path: "testimonial.author_role", label: "Author role", type: "text", group: "Testimonial" },
  { path: "testimonial.author_initials", label: "Author initials", type: "text", group: "Testimonial", maxLength: 3 },

  { path: "cta.title_prefix", label: "CTA title prefix", type: "text", group: "Call to Action" },
  { path: "cta.title_italic", label: "Italic accent", type: "text", group: "Call to Action" },
  { path: "cta.subtitle", label: "Subtitle", type: "textarea", group: "Call to Action" },
  { path: "cta.action_label", label: "Action label", type: "text", group: "Call to Action" },
  { path: "cta.phone_display", label: "Phone number", type: "text", group: "Call to Action" },
  {
    path: "cta.hours_text",
    label: "Hours / contact info",
    type: "textarea",
    group: "Call to Action",
    hint: "Use line breaks.",
  },

  { path: "footer.tagline", label: "Footer tagline", type: "textarea", group: "Footer", maxLength: 200 },
  { path: "footer.copyright", label: "Copyright line", type: "text", group: "Footer" },
  {
    path: "footer.columns",
    label: "Footer columns",
    type: "repeater",
    group: "Footer",
    minItems: 3,
    maxItems: 3,
    locked: "count",
    itemSchema: [
      { field: "title", label: "Column title", type: "text" },
      { field: "links", label: "Links", type: "link-list" },
    ],
  },
  {
    path: "footer.legal_links",
    label: "Legal links",
    type: "repeater",
    group: "Footer",
    maxItems: 6,
    itemSchema: [
      { field: "label", label: "Label", type: "text" },
      { field: "href", label: "URL", type: "text" },
    ],
  },

  {
    path: "theme.primary_color",
    label: "Accent color",
    type: "color",
    group: "Theme",
    hint: "Used for italic accents, buttons, highlights.",
  },
  { path: "theme.ink_color", label: "Ink (dark) color", type: "color", group: "Theme" },
  { path: "theme.paper_color", label: "Paper (background) color", type: "color", group: "Theme" },
];

export const NORTHFIELD_EDITOR_GROUPS = [
  "Brand",
  "Hero",
  "Quote Form",
  "Marquee",
  "Stats",
  "Services",
  "Projects",
  "Process",
  "Testimonial",
  "Call to Action",
  "Footer",
  "Theme",
] as const;
